[project]
name = "module-4-pydantic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = []

[tool.uv.workspace]
members = [
    "RAG_Pipeline",
]
