[project]
name = "ai-tools"
version = "0.1.0"
description = "A collection of tools for various applications."
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = []

[dependency-groups]
dev = [
    "jsonschema>=4.25.1",
    "pyyaml>=6.0.3",
]
